CREATE TABLE apolices(
    NUMERO SERIAL NOT NULL,
    TIPO_APOLICE VARCHAR(50) NOT NULL,
    DATA_VIGENCIA DATE NOT NULL,
    CONSTRAINT PK_APOLICES PRIMARY KEY (NUMERO)
);

CREATE TABLE enderecos(
    cep VARCHAR(10) NOT NULL,
    logradouro VARCHAR(150) NOT NULL,
    bairro VARCHAR(150) NOT NULL,
    cidade VARCHAR(150) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    CONSTRAINT PK_ENDERECOS PRIMARY KEY (cep)
);

CREATE TABLE segurados(
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(100) NOT NULL,
    endereco_cep VARCHAR(10) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    complemento VARCHAR(100),
    DATA_NASCIMENTO DATE NOT NULL,
    CONSTRAINT PK_SEGURADOS PRIMARY KEY (CPF),
    CONSTRAINT FK_SEGURADOS_endereco_cep FOREIGN KEY (endereco_cep) REFERENCES enderecos(cep)
);

CREATE TABLE apolices_segurados(
    NUMERO_APOLICE INTEGER NOT NULL,
    CPF_SEGURADO VARCHAR(14) NOT NULL,
    CONSTRAINT PK_APOLICES_SEGURADOS PRIMARY KEY (NUMERO_APOLICE, CPF_SEGURADO),
    CONSTRAINT FK_APOLICES FOREIGN KEY (NUMERO_APOLICE) REFERENCES apolices(NUMERO),
    CONSTRAINT FK_SEGURADOS FOREIGN KEY (CPF_SEGURADO) REFERENCES segurados(CPF)
);

CREATE TABLE servicos(
    CODIGO SERIAL NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    CONSTRAINT PK_SERVICOS PRIMARY KEY (CODIGO)
);

CREATE TABLE apolices_servicos(
    NUMERO_APOLICE INTEGER NOT NULL,
    CODIGO_SERVICO INTEGER NOT NULL,
    CONSTRAINT PK_APOLICES_SERVICOS PRIMARY KEY (NUMERO_APOLICE, CODIGO_SERVICO),
    CONSTRAINT FK_APOLICES_SERVICOS FOREIGN KEY (NUMERO_APOLICE) REFERENCES apolices(NUMERO),
    CONSTRAINT FK_SERVICOS FOREIGN KEY (CODIGO_SERVICO) REFERENCES servicos(CODIGO)
);