CREATE TABLE apolices(
    NUMERO SERIAL NOT NULL,
    TIPO_APOLICE VARCHAR(50) NOT NULL,
    DATA_VIGENCIA DATE NOT NULL,
    CONSTRAINT PK_APOLICES PRIMARY KEY (NUMERO)
);

CREATE TABLE segurados(
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CONSTRAINT PK_SEGURADOS PRIMARY KEY (CPF)
);

CREATE TABLE apolices_segurados(
    NUMERO_APOLICE INTEGER NOT NULL,
    CPF_SEGURADO VARCHAR(14) NOT NULL,
    CONSTRAINT PK_APOLICES_SEGURADOS PRIMARY KEY (NUMERO_APOLICE, CPF_SEGURADO),
    CONSTRAINT FK_APOLICES FOREIGN KEY (NUMERO_APOLICE) REFERENCES apolices(NUMERO),
    CONSTRAINT FK_SEGURADOS FOREIGN KEY (CPF_SEGURADO) REFERENCES segurados(CPF)
);

CREATE TABLE servicos(
    CODIGO SERIAL NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    CONSTRAINT PK_SERVICOS PRIMARY KEY (CODIGO)
);

CREATE TABLE apolices_servicos(
    NUMERO_APOLICE INTEGER NOT NULL,
    CODIGO_SERVICO INTEGER NOT NULL,
    CONSTRAINT PK_APOLICES_SERVICOS PRIMARY KEY (NUMERO_APOLICE, CODIGO_SERVICO),
    CONSTRAINT FK_APOLICES_SERVICOS FOREIGN KEY (NUMERO_APOLICE) REFERENCES apolices(NUMERO),
    CONSTRAINT FK_SERVICOS FOREIGN KEY (CODIGO_SERVICO) REFERENCES servicos(CODIGO)
);