name: "All In One"

on:
  push:
    branches:
      - "feature**"

jobs:
  call-workflow-ci-java-gradle:
    uses: kumabes-org/reusable-workflows-ci-java-maven/.github/workflows/ci.yml@main
    with:
      runs-on: "ubuntu-latest"
      environment: "develop"
      working-directory: "app"
      shell: "bash"
      project-name: "hands-on-01"
      java-distribution: "zulu"
      java-version: "21"
      maven-version: "3.9.9"
    secrets: inherit